package BankCORBA;

/**
* BankCORBA/BankHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Friday, 23 December 2022 11:08:08 o'clock WET
*/

public final class BankHolder implements org.omg.CORBA.portable.Streamable
{
  public BankCORBA.Bank value = null;

  public BankHolder ()
  {
  }

  public BankHolder (BankCORBA.Bank initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankCORBA.BankHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankCORBA.BankHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankCORBA.BankHelper.type ();
  }

}
