package BankCORBA;


/**
* BankCORBA/BankPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Friday, 23 December 2022 11:08:08 o'clock WET
*/

public abstract class BankPOA extends org.omg.PortableServer.Servant
 implements BankCORBA.BankOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("verser", new java.lang.Integer (0));
    _methods.put ("retirer", new java.lang.Integer (1));
    _methods.put ("getCompte", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BankCORBA/Bank/verser
       {
         double montant = in.read_double ();
         this.verser (montant);
         out = $rh.createReply();
         break;
       }

       case 1:  // BankCORBA/Bank/retirer
       {
         double montant = in.read_double ();
         this.retirer (montant);
         out = $rh.createReply();
         break;
       }

       case 2:  // BankCORBA/Bank/getCompte
       {
         BankCORBA.Compte $result = null;
         $result = this.getCompte ();
         out = $rh.createReply();
         BankCORBA.CompteHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BankCORBA/Bank:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Bank _this() 
  {
    return BankHelper.narrow(
    super._this_object());
  }

  public Bank _this(org.omg.CORBA.ORB orb) 
  {
    return BankHelper.narrow(
    super._this_object(orb));
  }


} // class BankPOA
