package BankCORBA;


/**
* BankCORBA/Bank.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Friday, 23 December 2022 11:08:08 o'clock WET
*/

public interface Bank extends BankOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Bank
