package BankCORBA;

/**
* BankCORBA/CompteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Friday, 23 December 2022 11:08:08 o'clock WET
*/

public final class CompteHolder implements org.omg.CORBA.portable.Streamable
{
  public BankCORBA.Compte value = null;

  public CompteHolder ()
  {
  }

  public CompteHolder (BankCORBA.Compte initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankCORBA.CompteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankCORBA.CompteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankCORBA.CompteHelper.type ();
  }

}
