package BankCORBA;


/**
* BankCORBA/cpteHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Friday, 23 December 2022 11:08:08 o'clock WET
*/

abstract public class cpteHelper
{
  private static String  _id = "IDL:BankCORBA/cpte:1.0";

  public static void insert (org.omg.CORBA.Any a, BankCORBA.Compte that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BankCORBA.Compte extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = BankCORBA.CompteHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (BankCORBA.cpteHelper.id (), "cpte", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BankCORBA.Compte read (org.omg.CORBA.portable.InputStream istream)
  {
    BankCORBA.Compte value = null;
    value = BankCORBA.CompteHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BankCORBA.Compte value)
  {
    BankCORBA.CompteHelper.write (ostream, value);
  }

}
