package BankCORBA;


/**
* BankCORBA/BankOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* Friday, 23 December 2022 12:05:17 o'clock WET
*/

public interface BankOperations 
{
  void verser (double montant);
  void retirer (double montant);
  BankCORBA.Compte getCompte ();
} // interface BankOperations
