package BankCORBA;


/**
* BankCORBA/Compte.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* Friday, 23 December 2022 12:05:17 o'clock WET
*/

public final class Compte implements org.omg.CORBA.portable.IDLEntity
{
  public int code = (int)0;
  public double solde = (double)0;

  public Compte ()
  {
  } // ctor

  public Compte (int _code, double _solde)
  {
    code = _code;
    solde = _solde;
  } // ctor

} // class Compte
