module BankCORBA{

	struct Compte {
		long code;
		double solde;
	};
	
	typedef Compte cpte;
	
	interface Bank {
		
		void verser(in double montant);
		void retirer(in double montant);
		
		cpte getCompte();		
		
	};
};